language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: XABxNanu29SepXbMCN3L3u0c9mtGxyDHzsDiKPTtjVlvoMYAhvyDMWHzfhktoP/t/3FdMw7LnxHfEHq30GNJGG/Ye8cGyVrNUfiYjYEyLyHR6uKBo0iNzFm2BZEXRN570/TZXwYtxYHu79HJnwbG3mxJYK0ubuIOccXT9qhLciWojXH4RVZT4H0CitUlFnsm41l1x4oDsOZex9n1XwdpCuR8lmx1sm6Ys3lQKxfgUs9w59/8P2a/pDyfBgJ7nakdJP89Kjg1sK8jakpcfgD3oxGwW4NeeiFU2utv8SHo6HX9lc4a5dN7dFdfozoQXeVAdA49IXvY7dNt9vuMjrcbGgNJt4YNeNh2jnRm7RpfLL43PhvtRysMmuRNWhP2GJ3s6MGj/lKizRceZMvoBXGh2UShVnP/pLjyYAjeNRkIgqc8MA8FmoF10odYZubcgMgSsYlAhC0DiKpiBJRqcUpEXsM16QJlP6+Sji46kZCOpFkBSfjH/NB6LqjqdvOgsIQXYeGpAHQ9LciVcTJgSd7Q5b2JBbLybtYabclAgJ0iEGMNFlBVYxGcQTzoFOYX23tHie84mxiBxQhI0LU7FV/zmdbtDg9kwVzRmThQ+NRSYokMfwxu4/+6CVE4uQUqzBU6oV933pHsOFaSWmaOwu44r1x5Jdll7awfgOy3JNJyJuE=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then travis_wait 100 Rscript -e 'covr::coveralls(type
  = "all")' ; fi
