language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
os:
- linux
- osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: ImDmvw8u6MYxIMkwi2pdP55wBF8PbY0ZQMkhqf3qbcW0RSstclOHuMc3aHoO3rLHGPk+JBzmiobgQFpgFvzrNcl3o065PJWHTYMkZCfkP4nPcWxaoH504NgA34gbJhQ0sYyX33MHVU28RWiNlwMnbclPiEHyiS8NAFA4+fwnX1tvtfmDgZhHtCq0mXFCTT31UpzPzZOIT/coRiQngy/p/l8nnIqW66QwbtmmzM1s4sbQ2FID2TMC22qecyOTSB0F/W45ULijzJepCBrap889Am04v0r8U/yyO7D0fwKIeG61j72CsHx1OEkg3nw043lGLyL4GDmoSnYOSvTYRrAv+81cqu+sOLgOGPqk67NHvjU0vnNj4CvOV9F1FUiP7pYqjgqMmwEhDS+lDz7xgWL4gGiXcWD13AT4nzDLU6fMcFfKfOCEXWRfcZRaly/GRX+xzkiVdfBAklDUl11Q8LIVhcGGp6G4HWskmbTyfWL9ppMCgdExUjy3dpF5ZHmtIo4QWqjqAelNJWYorMZ3zWgiDD6mQXpPJqTjm650YIY/cyVFbv58GtHdYi/I4IYmWrSvhCEfC5nbsR32wuG+XD9ElLonLwU3+2a2AwUacTEIll83laREF2OLLYtaajksoweJtQlt/c9dp0GiGNxIjtQuUAiLXwj1bLmThqd8ePqqxp0=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
