language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" ]]; then shopt -s expand_aliases ; x=`Rscript
  -e "cat(Sys.which('R'))"` ; alias R="travis_wait 100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: kwOeZr/tPDgh+MhTEPUXHA1esqyawHUjji1axpaYiKF0Avg7nX9+aT3GVCg/kdKSzjM6++Z69I5hdFGCpTv7/Jrxb57uFl2R74zgsuikvG1X7hb2dHA+J2S6OAkRcU9BCbd7JxpcrK0h0JKud7WWYDSdBho4c8dWcbHlv3YSa830Xp7/6vpoS3yWTP9AYbnu2hEIZ0GeYuW7194qrnBkUW90GR1rcOb31bCTo7n54NWb/k9NLIj7mKnvOF0PVn10wAIwnevN65z1elCxj8nX8pqMhhigPBhTj8trzik8cOY36x/0UGDCPhGQ3kgKIsc6xaDVEECMofLTl1Unv7urT43VAuBXoGW8bldNmbsrTC/oTtj+CddXhfoaSB7f/0DC79M/iYh/Zqu3lGT6k5PvokREIOnDAzhxowwX5uCOjBmVlpOQIo+n6IWfbt4DGO0MqH3hqStGJ/MwVhEpCpRL24uX3ukTiL3LFa6JMgjqXuXERTogtbUbM49m/fEPK4VGEbQJmWaaBH/1NqhUT6mlVTgejzedGBtXU9AwjAJyOw1pIREgmAWsSC5kR+NgBVbXHQCfiGbU9u34Tg/z4ilN4IFZKuCtCmKIf9rYHHZWvcPXe087K/Y5UDZ3Qp5VnhE+Sl5vO1J9WnhKd9aEx2tfb6CJa/1e6gDk6SfGwjOu478=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then echo 'covr::coveralls(type = "all")'
  > neuroc_covr.R ; travis_wait 100 Rscript neuroc_covr.R ; rm neuroc_covr.R ; fi
